export enum Department {
  RESERVATIONS = "RESERVATIONS",
  CUSTOMER_SERVICE = "CUSTOMER_SERVICE",
  ACCOUNTING = "ACCOUNTING",
  FINANCE = "FINANCE",
  MARKETING = "MARKETING",
  SALES = "SALES",
  TECHNOLOGY = "TECHNOLOGY",
  PRODUCT_DEVELOPMENT = "PRODUCT_DEVELOPMENT",
  DATA_ANALYTICS = "DATA_ANALYTICS",
  REVENUE_MANAGEMENT = "REVENUE_MANAGEMENT",
  OPERATIONS = "OPERATIONS",
  HUMAN_RESOURCES = "HUMAN_RESOURCES",
  LEGAL = "LEGAL",
  QUALITY_ASSURANCE = "QUALITY_ASSURANCE",
  CONTENT_MANAGEMENT = "CONTENT_MANAGEMENT",
  PARTNER_RELATIONS = "PARTNER_RELATIONS",
  CORPORATE_TRAVEL = "CORPORATE_TRAVEL",
  LOYALTY_PROGRAM = "LOYALTY_PROGRAM",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  LOCKED = "LOCKED",
}

export enum UserTypeEnum {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  SALESMAN = "SALESMAN",
  RESERVATION = "RESERVATION",
  ACCOUNTANT = "ACCOUNTANT",
  DEVELOPER = "DEVELOPER",
}

export enum Bank {
  Agrani_Bank_PLC = "Agrani Bank PLC",
  BASIC_Bank_PLC = "BASIC Bank PLC",
  Bangladesh_Development_Bank_PLC = "Bangladesh Development Bank PLC",
  Bangladesh_Krishi_Bank = "Bangladesh Krishi Bank",
  Janata_Bank_PLC = "Janata Bank PLC",
  Rupali_Bank_PLC = "Rupali Bank PLC",
  Sonali_Bank_PLC = "Sonali Bank PLC",
  Rajshahi_Krishi_Unnayan_Bank = "Rajshahi Krishi Unnayan Bank",
  Probashi_Kallyan_Bank = "Probashi Kallyan Bank",
  AB_Bank_PLC = "AB Bank PLC",
  Bangladesh_Commerce_Bank_Limited = "Bangladesh Commerce Bank Limited",
  Bank_Asia_PLC = "Bank Asia PLC",
  Bengal_Commercial_Bank_Limited = "Bengal Commercial Bank Limited",
  BRAC_Bank_PLC = "BRAC Bank PLC",
  City_Bank_PLC = "City Bank PLC",
  Community_Bank_Bangladesh_PLC = "Community Bank Bangladesh PLC",
  Citizens_Bank_PLC = "Citizens Bank PLC",
  Dhaka_Bank_PLC = "Dhaka Bank PLC",
  Dhaka_Mercantile_Co_Operative_Bank_Limited = "Dhaka Mercantile Co Operative Bank Limited",
  Dutch_Bangla_Bank_PLC = "Dutch Bangla Bank PLC",
  Eastern_Bank_PLC = "Eastern Bank PLC",
  IFIC_Bank_PLC = "IFIC Bank PLC",
  Jamuna_Bank_Limited = "Jamuna Bank Limited",
  Meghna_Bank_PLC = "Meghna Bank PLC",
  Mercantile_Bank_PLC = "Mercantile Bank PLC",
  Midland_Bank_Limited = "Midland Bank Limited",
  Modhumoti_Bank_Limited = "Modhumoti Bank Limited",
  Mutual_Trust_Bank_PLC = "Mutual Trust Bank PLC",
  National_Credit_Commerce_Bank_PLC = "National Credit Commerce Bank PLC",
  National_Bank_Limited = "National Bank Limited",
  NRB_Bank_Limited = "NRB Bank Limited",
  NRBC_Bank_PLC = "NRBC Bank PLC",
  ONE_Bank_PLC = "ONE Bank PLC",
  Padma_Bank_Limited = "Padma Bank Limited",
  Premier_Bank_PLC = "Premier Bank PLC",
  Prime_Bank_PLC = "Prime Bank PLC",
  Pubali_Bank_PLC = "Pubali Bank PLC",
  Shimanto_Bank_Limited = "Shimanto Bank Limited",
  South_Bangla_Agriculture_and_Commerce_Bank_Limited = "South Bangla Agriculture and Commerce Bank Limited",
  Southeast_Bank_Limited = "Southeast Bank Limited",
  Trust_Bank_PLC = "Trust Bank PLC",
  United_Commercial_Bank_PLC = "United Commercial Bank PLC",
  Uttara_Bank_PLC = "Uttara Bank PLC",
  Al_Arafah_Islami_Bank_PLC = "Al Arafah Islami Bank PLC",
  EXIM_Bank_PLC = "EXIM Bank PLC",
  First_Security_Islami_Bank_PLC = "First Security Islami Bank PLC",
  Global_Islami_Bank_PLC = "Global Islami Bank PLC",
  ICB_Islamic_Bank_PLC = "ICB Islamic Bank PLC",
  Islami_Bank_Bangladesh_PLC = "Islami Bank Bangladesh PLC",
  Shahjalal_Islami_Bank_PLC = "Shahjalal Islami Bank PLC",
  Social_Islami_Bank_PLC = "Social Islami Bank PLC",
  Standard_Bank_PLC = "Standard Bank PLC",
  Union_Bank_PLC = "Union Bank PLC",
  Bank_Al_Falah_Limited_Pakistan = "Bank Al Falah Limited Pakistan",
  Citibank_NA_United_States = "Citibank NA United States",
  Commercial_Bank_of_Ceylon_PLC_Sri_Lanka = "Commercial Bank of Ceylon PLC Sri Lanka",
  Habib_Bank_Limited_Pakistan = "Habib Bank Limited Pakistan",
  HSBC_United_Kingdom = "HSBC United Kingdom",
  National_Bank_of_Pakistan_Pakistan = "National Bank of Pakistan Pakistan",
  Standard_Chartered_Bank_United_Kingdom = "Standard Chartered Bank United Kingdom",
  State_Bank_of_India_India = "State Bank of India India",
  Woori_Bank_South_Korea = "Woori Bank South Korea",
  Ansar_VDP_Unnayan_Bank = "Ansar VDP Unnayan Bank",
  Karmasangsthan_Bank = "Karmasangsthan Bank",
  Grameen_Bank = "Grameen Bank",
  Jubilee_Bank = "Jubilee Bank",
  Palli_Sanchay_Bank = "Palli Sanchay Bank",
}

export enum ProductType {
  FLIGHT = "FLIGHT",
  HOTEL = "HOTEL",
  FOOD = "FOOD",
  TOUR_PACKAGE = "TOUR_PACKAGE",
  TRANSPORT = "TRANSPORT",
  VISA = "VISA",
  SPECIALIZED_TRAVEL = "SPECIALIZED_TRAVEL",
  OTHERS = "OTHERS",
}

export enum TourTransportType {
  FLIGHT = "FLIGHT",
  TRAIN = "TRAIN",
  BUS = "BUS",
  CAR = "CAR",
  SHIP = "SHIP",
  BOAT = "BOAT",
}

export enum TourMealType {
  BREAKFAST = "BREAKFAST",
  LUNCH = "LUNCH",
  DINNER = "DINNER",
  SNACK = "SNACK",
  VEGETARIAN = "VEGETARIAN",
  VEGAN = "VEGAN",
}

export enum AccommodationType {
  HOTEL = "HOTEL",
  MOTEL = "MOTEL",
  RESORT = "RESORT",
  VILLA = "VILLA",
  GUESTHOUSE = "GUESTHOUSE",
  APARTMENT = "APARTMENT",
}

export enum RoomType {
  SINGLE = "SINGLE",
  DOUBLE = "DOUBLE",
  TWIN = "TWIN",
  TRIPLE = "TRIPLE",
  QUAD = "QUAD",
  QUEEN = "QUEEN",
  KING = "KING",
  SUITE = "SUITE",
  DELUXE = "DELUXE",
  STUDIO = "STUDIO",
  APARTMENT = "APARTMENT",
  FAMILY = "FAMILY",
  DORMITORY = "DORMITORY",
  VILLA = "VILLA",
}

export enum VisaCategory {
  TOURIST = "TOURIST",
  BUSINESS = "BUSINESS",
  STUDENT = "STUDENT",
  WORK = "WORK",
  TRANSIT = "TRANSIT",
  DIPLOMATIC = "DIPLOMATIC",
  OTHER = "OTHER",
}

export enum EntryType {
  SINGLE = "SINGLE",
  DOUBLE = "DOUBLE",
  MULTIPLE = "MULTIPLE",
}

export enum ExpenseHeadCategory {
  ADMINISTRATIVE = "ADMINISTRATIVE",
  ASSETS = "ASSETS",
  DIRECT = "DIRECT",
  ENTERTAINMENT = "ENTERTAINMENT",
  INDIRECT = "INDIRECT",
  INSURANCE = "INSURANCE",
  MAINTENANCE = "MAINTENANCE",
  MARKETING = "MARKETING",
  MISCELLANEOUS = "MISCELLANEOUS",
  OFFICE = "OFFICE",
  OTHER = "OTHER",
  RENT = "RENT",
  SALARIES = "SALARIES",
  SELLING = "SELLING",
  TAXES = "TAXES",
  TRAVEL = "TRAVEL",
  UTILITIES = "UTILITIES",
}

export enum VisaServiceCharges {
  SERVICE_CHARGE = "Service Charge",
  NOTARY = "Notary",
  INSURANCE = "Insurance",
  ASSET_VALUATION = "Asset Valuation",
  APPOINT_FEE = "Appointment Fee",
  APPLICATION_FEE = "Application Fee",
  LEGAL = "Legal",
  MEDICAL = "Medical",
  CONSULAR = "Consular",
  TRAVEL = "Travel",
  FINANCIAL = "Financial",
  GOVERNMENT = "Government",
  OTHERS = "Others",
}
