export const modulePermission = [
  {
    name: "Dashboard",
    key: "dashboard",
    description: "Dashboard report",
    actions: ["READ"],
  },
  {
    name: "Invoice Tour Package",
    key: "invoice_tour_package",
    description: "Tour package invoice management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    name: "Invoice Visa",
    key: "invoice_visa",
    description: "Visa invoice management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    name: "Invoice Air Ticket",
    key: "invoice_air_ticket",
    description: "Air ticket invoice management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    name: "Invoice Hotel",
    key: "invoice_hotel",
    description: "Hotel invoice management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    name: "Refunds",
    key: "refunds",
    description: "Refunds management",
    actions: [],
  },
  {
    parentModuleKey: "refunds",
    name: "Air Ticket Refund",
    key: "air_ticket_refund",
    description: "Air ticket refund management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "refunds",
    name: "Tour Package Refund",
    key: "tour_package_refund",
    description: "Tour package refund management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    name: "Accounts",
    key: "accounts",
    description: "Accounts management",
    actions: [],
  },
  {
    parentModuleKey: "accounts",
    name: "Account",
    key: "account",
    description: "Accounts management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "accounts",
    name: "Receive Voucher",
    key: "receive_voucher",
    description: "Accounts management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "accounts",
    name: "Payment Voucher",
    key: "payment_voucher",
    description: "Accounts management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "accounts",
    name: "Contra Voucher",
    key: "contra_voucher",
    description: "Accounts management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "accounts",
    name: "Journal Voucher",
    key: "journal_voucher",
    description: "Accounts management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "accounts",
    name: "Adjustment Voucher",
    key: "adjustment_voucher",
    description: "Accounts management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "accounts",
    name: "Cheque Management",
    key: "cheque_management",
    description: "Cheque management",
    actions: ["READ", "UPDATE"],
  },

  {
    name: "Clients",
    key: "clients",
    description: "Clients management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    name: "Vendors",
    key: "vendors",
    description: "Vendors management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    name: "Agents",
    key: "agents",
    description: "Agents management",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    name: "Reports",
    key: "reports",
    description: "Reports management",
    actions: [],
  },
  {
    parentModuleKey: "reports",
    name: "System Logs",
    key: "system_logs",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "system_logs",
    name: "Audit Trails",
    key: "audit_trails",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Ledgers",
    key: "ledgers",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "ledgers",
    name: "Account Ledger",
    key: "account_ledger",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "ledgers",
    name: "Client Ledger",
    key: "client_ledger",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "ledgers",
    name: "Vendor Ledger",
    key: "vendor_ledger",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "ledgers",
    name: "Agent Ledger",
    key: "agent_ledger",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Sales Report",
    key: "sales_report",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "sales_report",
    name: "Sales Report",
    key: "sales_reports",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Invoice Tour Report",
    key: "invoice_tour_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Invoice Visa Report",
    key: "invoice_visa_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Invoice Air Ticket Report",
    key: "invoice_air_ticket_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Invoice Hotel Report",
    key: "invoice_hotel_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Visa Item Report",
    key: "visa_item_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Air Ticket Item Report",
    key: "air_ticket_item_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Hotel Item Report",
    key: "hotel_item_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Transport Item Report",
    key: "transport_item_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Food Item Report",
    key: "food_item_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "sales_report",
    name: "Invoice Others Report",
    key: "invoice_others_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Account Report",
    key: "account_reports",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "account_reports",
    name: "Account Report",
    key: "account_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "account_reports",
    name: "Account Statement",
    key: "account_statement",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Client Wise Due/Advance",
    key: "client_wise_due_advance",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Vendor Wise Due/Advance",
    key: "vendor_wise_due_advance",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Receive Voucher Report",
    key: "receive_voucher_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Payment Voucher Report",
    key: "payment_voucher_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Expense Report",
    key: "expense_report",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Day Book",
    key: "day_book",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Balance Sheet",
    key: "balance_sheet",
    description: "",
    actions: ["READ"],
  },
  {
    parentModuleKey: "reports",
    name: "Overall Profit/Loss",
    key: "overall_profit_loss",
    description: "",
    actions: ["READ"],
  },
  {
    name: "Configuration",
    key: "configuration",
    description: "System configuration",
    actions: [],
  },
  {
    parentModuleKey: "configuration",
    name: "Products",
    key: "products",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "products",
    name: "Product",
    key: "product",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "products",
    name: "Inventory",
    key: "inventory",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    parentModuleKey: "configuration",
    name: "Passport",
    key: "passport",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "configuration",
    name: "Employee",
    key: "employee",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    parentModuleKey: "configuration",
    name: "Users",
    key: "users",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "users",
    name: "User",
    key: "user",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "users",
    name: "Role/Permission",
    key: "role_permission",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    parentModuleKey: "configuration",
    name: "Tour Groups",
    key: "tour_groups",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },
  {
    parentModuleKey: "configuration",
    name: "Expense Head",
    key: "expense_head",
    description: "",
    actions: ["CREATE", "READ", "UPDATE", "DELETE"],
  },

  {
    parentModuleKey: "configuration",
    name: "Company",
    key: "company",
    description: "",
    actions: [],
  },
  {
    parentModuleKey: "company",
    name: "Company_info",
    key: "company_info",
    description: "",
    actions: ["READ", "UPDATE"],
  },
  {
    parentModuleKey: "company",
    name: "Company Config",
    key: "company_config",
    description: "",
    actions: ["READ", "UPDATE"],
  },

  {
    parentModuleKey: "configuration",
    name: "Database Backup",
    key: "database_backup",
    description: "Database backup management",
    actions: ["READ"],
  },
];
